{
 "title": "Knative Serving - Scaling Debugging",
 "description": "Knative Serving - Scaling Debugging",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\"}, namespace)"
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, label_serving_knative_dev_configuration)"
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_serving_knative_dev_configuration=\"$configuration\"}, label_serving_knative_dev_revision)"
   }
  ]
 },
 "panels": [
  {
   "title": "Knative Serving - Scaling Debugging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Autoscaler: Actual Pods (KPA)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})"
    }
   ]
  },
  {
   "title": "Autoscaler: Request Pods (KPA)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_desired{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})"
    }
   ]
  },
  {
   "title": "Autoscaler: Pending Pods (KPA)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_pending_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})"
    }
   ]
  },
  {
   "title": "Autoscaler: Not Ready Pods (KPA)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_not_ready_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})"
    }
   ]
  },
  {
   "title": "Autoscaler: Terminating Pods (KPA)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_terminating_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})"
    }
   ]
  },
  {
   "title": "Autoscaler: Desired Pods (KPA)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_desired{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})"
    }
   ]
  },
  {
   "title": "Autoscaler: Revision Pod Counts (Timeline)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_pods_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "Actual Pods"
    },
    {
     "expr": "sum(kn_revision_pods_requested{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "Requested Pods"
    },
    {
     "expr": "sum(kn_revision_pods_pending_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "Pending Pods"
    },
    {
     "expr": "sum(kn_revision_pods_not_ready_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "NotReady Pods"
    },
    {
     "expr": "sum(kn_revision_pods_terminating_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "Terminating Pods"
    }
   ]
  },
  {
   "title": "Autoscaler: Observed Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_concurrency_stable{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "request concurrency"
    },
    {
     "expr": "sum(kn_revision_concurrency_panic{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "panic concurrency"
    },
    {
     "expr": "sum(kn_revision_concurrency_target{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "target concurrency"
    },
    {
     "expr": "sum(kn_revision_capacity_excess{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "excess burst capacity"
    }
   ]
  },
  {
   "title": "Autoscaler: Scrape Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(kn_autoscaler_scrape_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(rate(kn_autoscaler_scrape_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(kn_autoscaler_scrape_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(kn_autoscaler_scrape_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p99)"
    }
   ]
  },
  {
   "title": "Autoscaler: Panic Mode",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_panic_mode{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"} )",
     "legendFormat": "panic mode (1 if autoscaler is in panic mode, 0 otherwise)"
    }
   ]
  },
  {
   "title": "Autoscaler: Observed RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_rps_stable{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "average RPS"
    },
    {
     "expr": "sum(kn_revision_rps_panic{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "average panic RPS"
    },
    {
     "expr": "sum(kn_revision_rps_target{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "target RPS"
    }
   ]
  },
  {
   "title": "Activator: Request Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kn_revision_request_concurrency{k8s_namespace_name=\"$namespace\", kn_configuration_name=\"$configuration\", kn_revision_name=\"$revision\"})",
     "legendFormat": "request concurrency"
    }
   ]
  },
  {
   "title": "Activator: Request Count by Response Code (last minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_count{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (http_response_status_code))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Activator: Response Time (last minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(http_server_request_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(rate(http_server_request_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(http_server_request_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(http_server_request_duration_bucket{k8s_namespace_name=\"$namespace\", kn_configuration_name=~\"$configuration\",kn_revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p99)"
    }
   ]
  }
 ]
}