{
 "title": "Knative Serving - Revision Queue Proxy Metrics",
 "tags": [ "Knative" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\"}, namespace)"
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\", namespace=\"$namespace\"}, label_serving_knative_dev_configuration)"
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\", namespace=\"$namespace\", label_serving_knative_dev_configuration=\"$configuration\"}, label_serving_knative_dev_revision)"
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(kube_deployment_labels{label_serving_knative_dev_configuration=~\"$configuration\", label_serving_knative_dev_revision=\"$revision\", namespace=\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Queue proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application: Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m]))"
    }
   ]
  },
  {
   "title": "Application: Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\", response_code_class=\"2xx\"}[1m])) / sum(rate(revision_app_request_count{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m]))"
    }
   ]
  },
  {
   "title": "Application: Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Application: Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\", response_code_class!=\"2xx\"}[1m])) / sum(rate(revision_app_request_count{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m]))"
    }
   ]
  },
  {
   "title": "Application: Request processing Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of request latency latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(revision_app_request_latencies_bucket{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(revision_app_request_latencies_bucket{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(revision_app_request_latencies_bucket{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(revision_app_request_latencies_bucket{namespace=\"$namespace\", revision_name=~\"$revision.*\", configuration_name=~\"$configuration.*\", container_name=\"queue-proxy\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}