// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/openshift/api/config/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImageDigestMirrorSets implements ImageDigestMirrorSetInterface
type FakeImageDigestMirrorSets struct {
	Fake *FakeConfigV1
}

var imagedigestmirrorsetsResource = v1.SchemeGroupVersion.WithResource("imagedigestmirrorsets")

var imagedigestmirrorsetsKind = v1.SchemeGroupVersion.WithKind("ImageDigestMirrorSet")

// Get takes name of the imageDigestMirrorSet, and returns the corresponding imageDigestMirrorSet object, and an error if there is any.
func (c *FakeImageDigestMirrorSets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ImageDigestMirrorSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(imagedigestmirrorsetsResource, name), &v1.ImageDigestMirrorSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ImageDigestMirrorSet), err
}

// List takes label and field selectors, and returns the list of ImageDigestMirrorSets that match those selectors.
func (c *FakeImageDigestMirrorSets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ImageDigestMirrorSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(imagedigestmirrorsetsResource, imagedigestmirrorsetsKind, opts), &v1.ImageDigestMirrorSetList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ImageDigestMirrorSetList{ListMeta: obj.(*v1.ImageDigestMirrorSetList).ListMeta}
	for _, item := range obj.(*v1.ImageDigestMirrorSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageDigestMirrorSets.
func (c *FakeImageDigestMirrorSets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(imagedigestmirrorsetsResource, opts))
}

// Create takes the representation of a imageDigestMirrorSet and creates it.  Returns the server's representation of the imageDigestMirrorSet, and an error, if there is any.
func (c *FakeImageDigestMirrorSets) Create(ctx context.Context, imageDigestMirrorSet *v1.ImageDigestMirrorSet, opts metav1.CreateOptions) (result *v1.ImageDigestMirrorSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(imagedigestmirrorsetsResource, imageDigestMirrorSet), &v1.ImageDigestMirrorSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ImageDigestMirrorSet), err
}

// Update takes the representation of a imageDigestMirrorSet and updates it. Returns the server's representation of the imageDigestMirrorSet, and an error, if there is any.
func (c *FakeImageDigestMirrorSets) Update(ctx context.Context, imageDigestMirrorSet *v1.ImageDigestMirrorSet, opts metav1.UpdateOptions) (result *v1.ImageDigestMirrorSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(imagedigestmirrorsetsResource, imageDigestMirrorSet), &v1.ImageDigestMirrorSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ImageDigestMirrorSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImageDigestMirrorSets) UpdateStatus(ctx context.Context, imageDigestMirrorSet *v1.ImageDigestMirrorSet, opts metav1.UpdateOptions) (*v1.ImageDigestMirrorSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(imagedigestmirrorsetsResource, "status", imageDigestMirrorSet), &v1.ImageDigestMirrorSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ImageDigestMirrorSet), err
}

// Delete takes name of the imageDigestMirrorSet and deletes it. Returns an error if one occurs.
func (c *FakeImageDigestMirrorSets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(imagedigestmirrorsetsResource, name, opts), &v1.ImageDigestMirrorSet{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageDigestMirrorSets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(imagedigestmirrorsetsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ImageDigestMirrorSetList{})
	return err
}

// Patch applies the patch and returns the patched imageDigestMirrorSet.
func (c *FakeImageDigestMirrorSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ImageDigestMirrorSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(imagedigestmirrorsetsResource, name, pt, data, subresources...), &v1.ImageDigestMirrorSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ImageDigestMirrorSet), err
}
