{
 "title": "Knative Eventing - Channel",
 "tags": [ "Knative" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values((label_replace(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace!=\"unknown\"}, \"kn_channel_namespace\", \"$1\", \"kn_kafkachannel_namespace\", \"(.*)\") OR kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\"}), kn_channel_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "In-Memory Channel Aggregated Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "In-Memory Channel: Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\", kn_channel_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\", kn_channel_namespace=~\"$namespace\", http_response_status_code=~\"2.*\"}[1m])) / sum(rate(kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\", kn_channel_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\", kn_channel_namespace=~\"$namespace\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\", kn_channel_namespace=~\"$namespace\", http_response_status_code!~\"2.*\"}[1m])) / sum(rate(kn_eventing_dispatch_duration_seconds_count{job=\"imc-dispatcher-sm-service\", kn_channel_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "In-Memory Dispatcher: Event Dispatch Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kn_eventing_dispatch_duration_seconds_bucket{job=\"imc-dispatcher-sm-service\",kn_channel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kn_eventing_dispatch_duration_seconds_bucket{job=\"imc-dispatcher-sm-service\",kn_channel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kn_eventing_dispatch_duration_seconds_bucket{job=\"imc-dispatcher-sm-service\",kn_channel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kn_eventing_dispatch_duration_seconds_bucket{job=\"imc-dispatcher-sm-service\",kn_channel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kafka Channel Aggregated Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Kafka Channel: Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Channel: Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\", http_response_status_code=~\"2.*\"}[1m])) / sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Channel: Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Kafka Channel: Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", http_response_status_code!~\"2.*\", kn_kafkachannel_namespace=~\"$namespace\"}[1m])) / sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Dispatcher: Event Dispatch Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kn_eventing_dispatch_latency_ms_bucket{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kn_eventing_dispatch_latency_ms_bucket{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kn_eventing_dispatch_latency_ms_bucket{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kn_eventing_dispatch_latency_ms_bucket{job=\"kafka-channel-receiver-sm-service\", kn_kafkachannel_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}