{
 "title": "Knative Eventing - Source CPU, Memory and Network Usage",
 "description": "Knative Eventing - Source CPU, Memory and Network Usage",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_eventing_knative_dev_source=~\".+\"}, namespace)"
   },
   {
    "name": "scontroller",
    "label": "scontroller",
    "query": "label_values(kube_pod_labels{label_eventing_knative_dev_source=~\".+\", namespace=\"$namespace\"}, label_eventing_knative_dev_source)"
   },
   {
    "name": "SourceType",
    "label": "Source Type",
    "query": "label_values(label_replace(kube_pod_labels{namespace=\"$namespace\", label_eventing_knative_dev_source=\"$scontroller\"}, \"label_eventing_knative_dev_source\", \"$1$2\", \"label_eventing_knative_dev_source\", \"(.+)-(.+)-(controller)\"), label_eventing_knative_dev_source)"
   },
   {
    "name": "sprefix",
    "label": "Sprefix",
    "query": "label_values(label_replace(kube_pod_labels{namespace=\"$namespace\", label_eventing_knative_dev_source=\"$scontroller\"}, \"label_eventing_knative_dev_source\", \"$1$2\", \"label_eventing_knative_dev_source\", \"(.+)-(.+)-(controller)\"), label_eventing_knative_dev_source)"
   },
   {
    "name": "nameofSource",
    "label": "SourceName",
    "query": "label_values(kube_pod_labels{label_eventing_knative_dev_sourceName=~\".+\", label_eventing_knative_dev_source_name=\"\", namespace=\"$namespace\", label_eventing_knative_dev_source=\"$scontroller\"}, label_eventing_knative_dev_sourceName)"
   },
   {
    "name": "sourceName",
    "label": "SourceName",
    "query": "label_values(kube_pod_labels{label_eventing_knative_dev_source_name=~\".+\", label_eventing_knative_dev_sourceName=\"\", namespace=\"$namespace\", label_eventing_knative_dev_source=\"$scontroller\"}, label_eventing_knative_dev_source_name)"
   },
   {
    "name": "pod",
    "label": "SourcePodName",
    "query": "label_values(kube_pod_labels{label_eventing_knative_dev_source_name=\"$sourceName\", label_eventing_knative_dev_sourceName=\"\", namespace=\"$namespace\", label_eventing_knative_dev_source=\"$scontroller\"} or kube_pod_labels{label_eventing_knative_dev_sourceName=\"$nameofSource\", label_eventing_knative_dev_source_name=\"\", namespace=\"$namespace\", label_eventing_knative_dev_source=\"$scontroller\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Eventing Source Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total CPU Usage (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod|k8s_POD_pingsource-mt-adapter-.+\", container != \"POD\", container != \"\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$pod|k8s_POD_pingsource-mt-adapter-.+\", container != \"POD\", container != \"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Network I/O (avg/sec, over 1m window)",
   "type": "graph",
   "description": "Network I/O at the pod level",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", container=\"POD\", name=~\"k8s_POD_$pod.+|k8s_POD_pingsource-mt-adapter-.+\"}[1m]))",
     "legendFormat": "received bytes"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", container=\"POD\", name=~\"k8s_POD_$pod.+|k8s_POD_pingsource-mt-adapter-.+\"}[1m]))",
     "legendFormat": "transmitted bytes"
    }
   ]
  },
  {
   "title": "Total Network Errors (avg/sec, over 1m window)",
   "type": "graph",
   "description": "Network I/O errors (avg/sec, over 1m window)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\", container=\"POD\", name=~\"k8s_POD_$pod.+|k8s_POD_pingsource-mt-adapter-.+\"}[1m]))",
     "legendFormat": "receive errors"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\", container=\"POD\", name=~\"k8s_POD_$pod.+|k8s_POD_pingsource-mt-adapter-.+\"}[1m]))",
     "legendFormat": "transmit errors"
    }
   ]
  }
 ]
}