{
 "title": "Knative Eventing - Source",
 "tags": [ "Knative" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values((http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\"} OR kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\"} OR http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\"}), kn_source_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "ApiServer Source Aggregated Metrics (per namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ApiServerSource: Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\", kn_source_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "ApiServerSource: Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\", kn_source_namespace=\"$namespace\", http_response_status_code=~\"2.*\"}[1m])) / sum(rate(http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\", kn_source_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "ApiServerSource: Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\", kn_source_namespace=\"$namespace\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "ApiServerSource: Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\", kn_source_namespace=\"$namespace\", http_response_status_code!~\"2.*\"}[1m])) / sum(rate(http_client_request_duration_seconds_count{job=\"apiserversource-sm-service\", kn_source_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "MT Ping Source Aggregated Metrics (per namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "MT PingSource: Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\", kn_source_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "MT PingSource: Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\", kn_source_namespace=\"$namespace\", http_response_status_code=~\"2.*\"}[1m])) / sum(rate(http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\", kn_source_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "MT PingSource: Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\", kn_source_namespace=\"$namespace\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "MT PingSource: Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\", kn_source_namespace=\"$namespace\", http_response_status_code!~\"2.*\"}[1m])) / sum(rate(http_client_request_duration_seconds_count{job=\"pingsource-mt-adapter-sm-service\", kn_source_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Source Aggregated Metrics (per namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "KafkaSource: Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\", namespace=\"knative-eventing\", kn_kafkasource_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "KafkaSource: Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\", namespace=\"knative-eventing\", kn_kafkasource_namespace=\"$namespace\", http_response_status_code=~\"2.*\"}[1m])) / sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\", namespace=\"knative-eventing\", kn_kafkasource_namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "KafkaSource: Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\", namespace=\"knative-eventing\", kn_kafkasource_namespace=\"$namespace\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "KafkaSource: Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\", namespace=\"knative-eventing\", kn_kafkasource_namespace=\"$namespace\", http_response_status_code!~\"2.*\"}[1m])) / sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-source-dispatcher-sm-service\", namespace=\"knative-eventing\", kn_kafkasource_namespace=\"$namespace\"}[1m]))"
    }
   ]
  }
 ]
}