{
 "title": "Knative Eventing - KafkaSink",
 "tags": [ "Knative" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", kn_kafkasink_namespace!=\"unknown\"}, kn_kafkasink_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "KafkaSink (kafka-sink-receiver) Aggregated Metrics (per namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "KafkaSink (kafka-sink-receiver): Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", kn_kafkasink_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "KafkaSink (kafka-sink-receiver): Success Rate (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", http_response_status_code=~\"2.*\", kn_kafkasink_namespace=~\"$namespace\"}[1m])) / sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", kn_kafkasink_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "KafkaSink (kafka-sink-receiver): Event Count by Event Type (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", kn_kafkasink_namespace=~\"$namespace\"}[1m])) by (cloudevents_type)",
     "legendFormat": "{{cloudevents_type}}"
    }
   ]
  },
  {
   "title": "KafkaSink (kafka-sink-receiver): Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", kn_kafkasink_namespace=~\"$namespace\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "KafkaSink (kafka-sink-receiver): Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", http_response_status_code!~\"2.*\", kn_kafkasink_namespace=~\"$namespace\"}[1m])) / sum(rate(kn_eventing_dispatch_latency_ms_count{job=\"kafka-sink-receiver-sm-service\", kn_kafkasink_namespace=~\"$namespace\"}[1m]))"
    }
   ]
  }
 ]
}