diff --git a/openshift-knative-operator/Dockerfile b/openshift-knative-operator/Dockerfile
index 947933da3..5476d9c86 100755
--- a/openshift-knative-operator/Dockerfile
+++ b/openshift-knative-operator/Dockerfile
@@ -19,6 +19,9 @@ ARG VERSION=
 COPY --from=builder /usr/bin/main /usr/bin/openshift-knative-operator
 COPY LICENSE /licenses/
 
+ENV KO_DATA_PATH="/var/run/ko"
+COPY openshift-knative-operator/cmd/openshift-knative-operator/kodata $KO_DATA_PATH
+
 USER 65532
 
 LABEL \
