// Code generated by injection-gen. DO NOT EDIT.

package route

import (
	context "context"

	factory "github.com/openshift-knative/serverless-operator/pkg/client/route/injection/informers/factory"
	v1 "github.com/openshift/client-go/route/informers/externalversions/route/v1"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
	logging "knative.dev/pkg/logging"
)

func init() {
	injection.Default.RegisterInformer(withInformer)
}

// Key is used for associating the Informer inside the context.Context.
type Key struct{}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := factory.Get(ctx)
	inf := f.Route().V1().Routes()
	return context.WithValue(ctx, Key{}, inf), inf.Informer()
}

// Get extracts the typed informer from the context.
func Get(ctx context.Context) v1.RouteInformer {
	untyped := ctx.Value(Key{})
	if untyped == nil {
		logging.FromContext(ctx).Panic(
			"Unable to fetch github.com/openshift/client-go/route/informers/externalversions/route/v1.RouteInformer from context.")
	}
	return untyped.(v1.RouteInformer)
}
