// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	fake "github.com/openshift-knative/serverless-operator/pkg/client/injection/informers/factory/fake"
	image "github.com/openshift-knative/serverless-operator/pkg/client/injection/informers/image/v1/image"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = image.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Image().V1().Images()
	return context.WithValue(ctx, image.Key{}, inf), inf.Informer()
}
