// Code generated by injection-gen. DO NOT EDIT.

package imagepolicy

import (
	context "context"

	factory "github.com/openshift-knative/serverless-operator/pkg/client/config/injection/informers/factory"
	v1 "github.com/openshift/client-go/config/informers/externalversions/config/v1"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
	logging "knative.dev/pkg/logging"
)

func init() {
	injection.Default.RegisterInformer(withInformer)
}

// Key is used for associating the Informer inside the context.Context.
type Key struct{}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := factory.Get(ctx)
	inf := f.Config().V1().ImagePolicies()
	return context.WithValue(ctx, Key{}, inf), inf.Informer()
}

// Get extracts the typed informer from the context.
func Get(ctx context.Context) v1.ImagePolicyInformer {
	untyped := ctx.Value(Key{})
	if untyped == nil {
		logging.FromContext(ctx).Panic(
			"Unable to fetch github.com/openshift/client-go/config/informers/externalversions/config/v1.ImagePolicyInformer from context.")
	}
	return untyped.(v1.ImagePolicyInformer)
}
