apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-422-override-snapshot-f4b69150
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-422
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-422
  components:
    - name: "serverless-index-137-fbc-422"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-422/serverless-index-137-fbc-422@sha256:d053ba0bb461831755cdc43b27e52dabce042caa13375079be1eb1cafb56228d"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "3ebe969709ce472093754d468ee2990671517450"
          dockerfileUrl: "Dockerfile"
