apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-50-override-snapshot-f9c3740a
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-50
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-50
  components:
    - name: "serverless-index-137-fbc-50"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-50/serverless-index-137-fbc-50@sha256:5f0ede9b5ba22ebeb980fa9619eae29e4313125a97e6fa4fbbc9447c98c98eac"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "66c69b03d4ce3e1a1d6fcd39293ead90524823ec"
          dockerfileUrl: "Dockerfile"
