apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-138-fbc-419-override-snapshot-e9755737
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-138-fbc-419
    branch: release-1.38
spec:
  application: serverless-operator-138-fbc-419
  components:
    - name: "serverless-index-138-fbc-419"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-138-fbc-419/serverless-index-138-fbc-419@sha256:5f2732eac75b8361e4d9b207b3655caeeff0991e561128580e074f6331124918"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "8fe1691095eaeed514f60572be9797eda3d38c09"
          dockerfileUrl: "Dockerfile"
