apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-414-override-snapshot-15b1fbe6
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-414
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-414
  components:
    - name: "serverless-index-137-fbc-414"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-414/serverless-index-137-fbc-414@sha256:64866d6ccb43a6857815f06b35d8010532852987e35d4468b9ea497b37aad971"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "5513054aae05feb65ae97fcd0261ffd73b460d83"
          dockerfileUrl: "Dockerfile"
