apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-419-override-snapshot-1c0a3e4a
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-419
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-419
  components:
    - name: "serverless-index-137-fbc-419"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-419/serverless-index-137-fbc-419@sha256:a241756bdfe56094756f68401bd999f1e5c5e98f2946879c1fffdfcb5561f555"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "a4188658f4c2e0473c9a5e5fd5a285099dcc10ef"
          dockerfileUrl: "Dockerfile"
