apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-136-fbc-415-override-snapshot-dbabc470
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-136-fbc-415
    branch: release-1.36
spec:
  application: serverless-operator-136-fbc-415
  components:
    - name: "serverless-index-136-fbc-415"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-136-fbc-415/serverless-index-136-fbc-415@sha256:53f10016864075f12dee5980e616f09947056ce275ed2789ecdf7a0b852c9464"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "614e5fd01b39117fd9925570dc88bd447b48b132"
          dockerfileUrl: "Dockerfile"
