apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-422-override-snapshot-3874fad7
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-422
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-422
  components:
    - name: "serverless-index-137-fbc-422"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-422/serverless-index-137-fbc-422@sha256:f4ad0a0a191920408f70e3c917fe5ab577d9c3f9c7f21086446b594a9e690275"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "f4f6c74cef608a2570a40bcf9176ae51a03dd3f6"
          dockerfileUrl: "Dockerfile"
