apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-135-fbc-416-override-snapshot-a138a3ec
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-135-fbc-416
spec:
  application: serverless-operator-135-fbc-416
  components:
    - name: "serverless-index-135-fbc-416"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-135-fbc-416/serverless-index-135-fbc-416@sha256:c81329a17f84dd6c3768010babc82a753711be962ab93154c86198fb9e8faa8a"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "4bf08d7303c7641ba73808c4129e272d974ccdd1"
          dockerfileUrl: "Dockerfile"
