apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-421-override-snapshot-fc932d56
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-421
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-421
  components:
    - name: "serverless-index-137-fbc-421"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-421/serverless-index-137-fbc-421@sha256:bea8c6b4b2ffa988b15868285caaa8354e559d2bd68f742a1472d3738f2c656a"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "8f606f01b9bea15c66ed057eeb3a0af1afea6fc4"
          dockerfileUrl: "Dockerfile"
