apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-416-override-snapshot-db901bdd
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-416
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-416
  components:
    - name: "serverless-index-137-fbc-416"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-416/serverless-index-137-fbc-416@sha256:d863945aef4cda11c52a3ab35716cc0f9b4387ba914c5840b6f65aefc5a6558b"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "404bb81ce28d12e06d97c87c928f65017b3cfc95"
          dockerfileUrl: "Dockerfile"
