apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-135-fbc-417-override-snapshot-b92baff5
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-135-fbc-417
spec:
  application: serverless-operator-135-fbc-417
  components:
    - name: "serverless-index-135-fbc-417"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-135-fbc-417/serverless-index-135-fbc-417@sha256:690c6e3325a1eccdb75c519ad8b9f6e2c6993fd570618a567db8077aa35806df"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "4bf08d7303c7641ba73808c4129e272d974ccdd1"
          dockerfileUrl: "Dockerfile"
