apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-417-override-snapshot-421f07a5
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-417
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-417
  components:
    - name: "serverless-index-137-fbc-417"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-417/serverless-index-137-fbc-417@sha256:ad523a28a4c55cda99159f8b95df03840fa94d6c2e113c6b308a1f22cc854fed"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "3ebe969709ce472093754d468ee2990671517450"
          dockerfileUrl: "Dockerfile"
