apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-50-override-snapshot-70b37d18
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-50
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-50
  components:
    - name: "serverless-index-137-fbc-50"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-50/serverless-index-137-fbc-50@sha256:241c447046013460d4a728e12c8766d17e18fa8826f93e59d7415011b0c703db"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "d8ec408174d56cdbd7360353580078733053b999"
          dockerfileUrl: "Dockerfile"
