apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-414-override-snapshot-afc8c364
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-414
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-414
  components:
    - name: "serverless-index-137-fbc-414"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-414/serverless-index-137-fbc-414@sha256:db6ebe0bb7b9799a2d15766214b59c8d9eeaeba973c5191288399de001e756f9"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "1b8fd13ca6e83309fd21246c64f72a6860945cef"
          dockerfileUrl: "Dockerfile"
