apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-138-override-snapshot-35a4a8c5
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-138
    branch: release-1.38
spec:
  application: serverless-operator-138
