apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-422-override-snapshot-5fe1f13c
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-422
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-422
  components:
    - name: "serverless-index-137-fbc-422"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-422/serverless-index-137-fbc-422@sha256:70dbad94b35616851ed5e8793f75c646f363a69f143c290ddbff6df23de9e577"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "3f2124844bf4e138a3c919e507cb1c1c12c55d7f"
          dockerfileUrl: "Dockerfile"
