apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-136-fbc-417-override-snapshot-01f95070
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-136-fbc-417
    branch: release-1.36
spec:
  application: serverless-operator-136-fbc-417
  components:
    - name: "serverless-index-136-fbc-417"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-136-fbc-417/serverless-index-136-fbc-417@sha256:9331bf3858c8e8a15658ac8f7af8ef2c435e26dc9cfe50c99141054ac420eadb"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "b7449836a9359799e057f03958f9ee577a0f627e"
          dockerfileUrl: "Dockerfile"
