apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-423-override-snapshot-f5d9af6e
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-423
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-423
  components:
    - name: "serverless-index-137-fbc-423"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-423/serverless-index-137-fbc-423@sha256:3e459367879c680d779a1b38c3fc42c526d532fa8c1c24cef085651681566b9a"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "66c69b03d4ce3e1a1d6fcd39293ead90524823ec"
          dockerfileUrl: "Dockerfile"
