apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-423-override-snapshot-772c7d9f
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-423
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-423
  components:
    - name: "serverless-index-137-fbc-423"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-423/serverless-index-137-fbc-423@sha256:17db40ede5aa896c4acc2b3ff18af7d64be079a45b0d3675945a5ed114fb62d7"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "8f606f01b9bea15c66ed057eeb3a0af1afea6fc4"
          dockerfileUrl: "Dockerfile"
