apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-415-override-snapshot-949a70b3
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-415
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-415
  components:
    - name: "serverless-index-137-fbc-415"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-415/serverless-index-137-fbc-415@sha256:f0be0e164b8717e18a96678918d5a3428b9fcda8cbef331540f9990eb6143bbf"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "08c31740998845f4e74527b543e2f801bbce6291"
          dockerfileUrl: "Dockerfile"
