apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-421-override-snapshot-deffa3c5
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-421
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-421
  components:
    - name: "serverless-index-137-fbc-421"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-421/serverless-index-137-fbc-421@sha256:205541fb2d26ba17f1dc88d5dc59f1b2342ef982741c862721b8e29734ce99ab"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "b17152e55cec43c4ca91d3a8d0c0e122c5ddc178"
          dockerfileUrl: "Dockerfile"
