apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-414-override-snapshot-35cd6d5d
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-414
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-414
  components:
    - name: "serverless-index-137-fbc-414"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-414/serverless-index-137-fbc-414@sha256:8c41fd2738838529c615b9fc401cb9dea5b7ab341e47b6abc65c0b8f0e1f6e0b"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "3ebe969709ce472093754d468ee2990671517450"
          dockerfileUrl: "Dockerfile"
