apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-138-fbc-421-override-snapshot-cc6ec719
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-138-fbc-421
    branch: release-1.38
spec:
  application: serverless-operator-138-fbc-421
  components:
    - name: "serverless-index-138-fbc-421"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-138-fbc-421/serverless-index-138-fbc-421@sha256:48faf9189d0b5bc52f2cd88ee0bc420ce25156b2666d50f0bdc16ffcfc59dee1"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "29716a3c61913b159fa860be99f199836f00eda5"
          dockerfileUrl: "Dockerfile"
