apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-416-override-snapshot-cc31fb65
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-416
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-416
  components:
    - name: "serverless-index-137-fbc-416"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-416/serverless-index-137-fbc-416@sha256:9f6efe7141c268c1a6197a3090b34756dcaf07287bf9f92331c881a58816fc46"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "3f2124844bf4e138a3c919e507cb1c1c12c55d7f"
          dockerfileUrl: "Dockerfile"
