apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-419-override-snapshot-10f28f6d
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-419
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-419
  components:
    - name: "serverless-index-137-fbc-419"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-419/serverless-index-137-fbc-419@sha256:8c115c4d162241038ffdd8d24a6f9c86399981267ea55bea6d67c37e30160889"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "f4f6c74cef608a2570a40bcf9176ae51a03dd3f6"
          dockerfileUrl: "Dockerfile"
