apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: serverless-operator-137-fbc-418-override-snapshot-084a3a39
  labels:
    test.appstudio.openshift.io/type: override
    application: serverless-operator-137-fbc-418
    branch: release-1.37
spec:
  application: serverless-operator-137-fbc-418
  components:
    - name: "serverless-index-137-fbc-418"
      containerImage: "quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-137-fbc-418/serverless-index-137-fbc-418@sha256:4e0eeaf4aa9d09bb0313a5d22aaec27374a214302b0bcfbb199c2997edad4a53"
      source:
        git:
          url: "https://github.com/openshift-knative/serverless-operator"
          revision: "5c77f531ff89f67f5882cb347d3a8cb9eeb8a50c"
          dockerfileUrl: "Dockerfile"
