diff --git a/knative-operator/Dockerfile b/knative-operator/Dockerfile
index 0fd4719f9..2aedacb3c 100755
--- a/knative-operator/Dockerfile
+++ b/knative-operator/Dockerfile
@@ -19,6 +19,8 @@ RUN microdnf install tzdata
 
 COPY --from=builder /usr/bin/main /usr/bin/knative-operator
 
+COPY knative-operator/deploy /deploy
+
 USER 65532
 
 LABEL \
