diff --git a/knative-operator/Dockerfile b/knative-operator/Dockerfile
index 044413409..f55fe650e 100755
--- a/knative-operator/Dockerfile
+++ b/knative-operator/Dockerfile
@@ -19,6 +19,8 @@ ARG VERSION=
 COPY --from=builder /usr/bin/main /usr/bin/knative-operator
 COPY LICENSE /licenses/
 
+COPY knative-operator/deploy /deploy
+
 USER 65532
 
 LABEL \
