{
 "title": "Knative Eventing - Broker/Trigger",
 "tags": [ "Knative" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventNamespace",
    "label": "namespace",
    "query": "label_values(mt_broker_ingress_event_count{namespace_name!=\"unknown\"}, namespace_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Broker (broker-ingress) Aggregated Metrics (per namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Broker (broker-ingress): Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mt_broker_ingress_event_count{namespace_name=~\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Broker (broker-ingress): Success Rate  (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mt_broker_ingress_event_count{response_code_class=\"2xx\", namespace_name=~\"$eventNamespace\"}[1m])) / sum(rate(mt_broker_ingress_event_count{namespace_name=~\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Broker (broker-ingress): Event Count by Event Type (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mt_broker_ingress_event_count{namespace_name=~\"$eventNamespace\"}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Broker (broker-ingress): Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mt_broker_ingress_event_count{namespace_name=~\"$eventNamespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Broker (broker-ingress): Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mt_broker_ingress_event_count{response_code_class!=\"2xx\", namespace_name=~\"$eventNamespace\"}[1m])) / sum(rate(mt_broker_ingress_event_count{namespace_name=~\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Broker (broker-ingress): Event Dispatch Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(mt_broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(mt_broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mt_broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Trigger (broker-filter) Aggregated Metrics (per namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Trigger (broker-filter): Event Count (avg/sec, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mt_broker_filter_event_count{namespace_name=~\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trigger (broker-filter): Success Rate  (2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mt_broker_filter_event_count{response_code_class=\"2xx\", namespace_name=~\"$eventNamespace\"}[1m])) / sum(rate(mt_broker_filter_event_count{namespace_name=~\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Broker (broker-filter): Event Count by Event Type (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mt_broker_filter_event_count{namespace_name=~\"$eventNamespace\"}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Trigger (broker-filter): Event Count by Response Code Class (avg/sec, over 1m window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mt_broker_filter_event_count{namespace_name=~\"$eventNamespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Trigger (broker-filter): Failure Rate (non-2xx Event, fraction rate, over 1m window)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mt_broker_filter_event_count{response_code_class!=\"2xx\", namespace_name=~\"$eventNamespace\"}[1m])) / sum(rate(mt_broker_filter_event_count{namespace_name=~\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trigger (broker-filter): Event Dispatch Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(mt_broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(mt_broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mt_broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Trigger (broker-filter): Event Processing Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(mt_broker_filter_event_processing_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(mt_broker_filter_event_processing_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_broker_filter_event_processing_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mt_broker_filter_event_processing_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}