{
 "title": "Knative Health Status",
 "description": "Knative Health status",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(knative_up{namespace!=\"unknown\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Knative Status",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(sum(knative_up{namespace=\"$namespace\", service=\"knative-openshift-metrics\"})/2)"
    }
   ]
  },
  {
   "title": "Knative Health Status - Serving",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "knative_up{namespace=\"$namespace\", service=\"knative-openshift-metrics\", type=\"serving_status\"}",
     "legendFormat": "Serving status - 1 is up, 0 is down"
    }
   ]
  },
  {
   "title": "Knative Health Status - Eventing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "knative_up{namespace=\"$namespace\", service=\"knative-openshift-metrics\", type=\"eventing_status\"}",
     "legendFormat": "Eventing status - 1 is up, 0 is down"
    }
   ]
  }
 ]
}