{
 "title": "Knative Eventing - Source",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_eventing_knative_dev_source=~\".+\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "ApiServerSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ApiServerSource: Event Count (rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "ApiServerSource: Success Rate (2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count{namespace=\"$namespace\", response_code_class=\"2xx\"}[1m])) / sum(rate(apiserversource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "ApiServerSource: Event Count by Response Code Class (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count{namespace=\"$namespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "ApiServerSource: Failure Rate (non-2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count{namespace=\"$namespace\", response_code_class!=\"2xx\"}[1m])) / sum(rate(apiserversource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  { "title": "MT PingSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MT PingSource: Event Count (rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "MT PingSource: Success Rate  (2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count{namespace=\"$namespace\", response_code_class=\"2xx\"}[1m])) / sum(rate(pingsource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "MT PingSource: Event Count by Response Code Class (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count{namespace=\"$namespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "MT PingSource: Failure Rate (non-2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count{namespace=\"$namespace\", response_code_class!=\"2xx\"}[1m])) / sum(rate(pingsource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  { "title": "KafkaSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Kafka: Event Count (rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafkasource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "KafkaSource: Success Rate (2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafkasource_event_count{namespace=\"$namespace\", response_code_class=\"2xx\"}[1m])) / sum(rate(kafkasource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "KafkaSource: Event Count by Response Code Class (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafkasource_event_count{namespace=\"$namespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "KafkaSource: Failure Rate (non-2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafkasource_event_count{namespace=\"$namespace\", response_code_class!=\"2xx\"}[1m])) / sum(rate(kafkasource_event_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  }
 ]
}