// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	fake "github.com/openshift-knative/serverless-operator/pkg/client/route/injection/informers/factory/fake"
	route "github.com/openshift-knative/serverless-operator/pkg/client/route/injection/informers/route/v1/route"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = route.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Route().V1().Routes()
	return context.WithValue(ctx, route.Key{}, inf), inf.Informer()
}
