project:
  name: serverless-operator
  # When bumping the Operator to a new version (major and minor), make sure to also update
  # all components in `dependencies.previous` to the same versions as `dependencies` in the same PR.
  # Otherwise, the upgrade tests will not pass, as we have a different SO version with the same bundle contents.
  # Also make sure to update values under `olm.previous` by copying from `olm.replaces` and `olm.skipRange`.
  version: 1.37.2
olm:
  replaces: 1.37.1
  skipRange: '>1.37.1 <1.37.2'
  channels:
    # The "global" operator default, used as "operators.operatorframework.io.bundle.channels.v1" annotation
    operator_default: stable
    # The default channel to use for CI
    default: stable
    list:
      - stable
      - stable-1.37
  previousBundles:
    # List of previous bundles to add to the generated index, also used in upgrade tests
    - version: 1.37.1
      replaces: 1.37.0
      skipRange: ">1.37.0 <1.37.1"
    - version: 1.37.0
      replaces: 1.36.1
      skipRange: ">=1.36.1 <1.37.0"
    - version: 1.36.1
      replaces: 1.36.0
      skipRange: ">=1.36.0 <1.36.1"
    - version: 1.36.0
      replaces: 1.35.0
      skipRange: ">=1.35.0 <1.36.0"
    - version: 1.35.0
      replaces: 1.34.0
      skipRange: ">=1.34.0 <1.35.0"
requirements:
  kube:
    # The min version validation in `vendor/knative.dev/pkg/version/version.go`
    # is ignored as it is overridden by fake version via KUBERNETES_MIN_VERSION.
    # This value is used for CSV's min version validation.
    minVersion: 1.25.0
  golang: '1.25'
  nodejs: 20.x
  ocpVersion:
    list:
      - "4.14"
      - "4.15"
      - "4.16"
      - "4.17"
      - "4.18"
      - "4.19"
      - "4.20"
      - "4.21"
      - "4.22"
      - "5.0"
      - "4.23"
    min: '4.14'
    # Version to use for OCP docs links (in CSV or Quickstarts)
    doc: '4.22'
    # deprecated, use requirements.ocpVersion.list[-1]
    max: '4.22'
    # version to use in Dockerfiles
    build: '4.22'
    label: 'v4.14'
    # OCP stream for kube-rbac-proxy image.
    kube-rbac-proxy: "4.17"
dependencies:
  serving: knative-v1.17
  # serving midstream branch name
  serving_artifacts_branch: release-v1.17
  # versions for networking components
  kourier: knative-v1.17
  net_kourier_artifacts_branch: release-v1.17
  net_istio: knative-v1.17
  net_istio_artifacts_branch: release-v1.17
  redhat-knative-istio-authz-chart: 1.37.0
  service_mesh_proxy: registry.redhat.io/openshift-service-mesh/proxyv2-rhel9@sha256:9232fe14a42d2e00069cdb4390f753609d765e90eafa9cabaa040caa017b6b72
  eventing: knative-v1.17
  # eventing core midstream branch name
  eventing_artifacts_branch: release-v1.17
  # eventing-kafka-broker promotion tag
  eventing_kafka_broker: knative-v1.17
  # eventing-kafka-broker midstream branch or commit
  eventing_kafka_broker_artifacts_branch: release-v1.17
  # eventing-integrations promotion tag
  eventing_integrations: knative-v1.17
  # eventing-integrations midstream branch or commit
  eventing_integrations_artifacts_branch: release-v1.17
  # eventing-istio promotion tag
  eventing_istio: knative-v1.17
  # eventing-istio midstream branch or commit
  eventing_istio_artifacts_branch: release-v1.17
  # backstage-plugins promotion tag
  backstage_plugins: knative-v1.17
  # backstage-plugins midstream branch or commit
  backstage_plugins_artifacts_branch: release-v1.17
  cli: knative-v1.17
  kube_rbac_proxy: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9@sha256:c9a8306c8de7881c673412a618732b1107aad2d21bcebb9bf2ea82ae3861b4f5
  func:
    promotion_tag: knative-v1.17
    # if additional image is added amend the list in hack/generate/catalog.sh
    tekton_buildah: registry.redhat.io/rhel9/buildah@sha256:f0432e506a8aea892078322518aedeb12e0f17504dbc29fd293cd8cda06e7f73
    nodejs_20_minimal: registry.access.redhat.com/ubi9/nodejs-20-minimal@sha256:87f2eb0ce06e922a7629fa94fad62ed4e6be05931852b779269e0692282a099e
    openjdk_21: registry.access.redhat.com/ubi9/openjdk-21@sha256:f957ec240a4d6d9e065562cede6994b6b8146be8c5247d3cbe42af819a933da8
    python-39: registry.access.redhat.com/ubi9/python-39@sha256:fca62bd0edb6011c8baf779577bf235cf49b215556cd9a9b7eccc9750aa89b17
  operator: 1.17.8
  # Previous versions required for downgrade testing
  previous:
    serving: knative-v1.17
    eventing: knative-v1.17
    eventing_kafka_broker: knative-v1.17
