// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	fake "github.com/openshift-knative/serverless-operator/pkg/client/injection/informers/factory/fake"
	imagestream "github.com/openshift-knative/serverless-operator/pkg/client/injection/informers/image/v1/imagestream"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = imagestream.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Image().V1().ImageStreams()
	return context.WithValue(ctx, imagestream.Key{}, inf), inf.Informer()
}
